### ISSUE TITLE
When in --loop mode add option to run command after each frame is captured.

### ISSUE THREAD

**Issue by Mike-Benoit** [fsphil/fswebcam#39]
It would be a nice feature to be able to run a command after each frame is captured when in --loop mode so we can do external processing on it, without having to jump through hoops to determine if the image is in the process of being written to or not.

**Comment by fsphil** [comment]
You can do this with the `--exec` argument:

`$ fswebcam -l 60 output.jpeg --exec "your command here"`

The order matters, to run your command after the image has been written the `--exec` needs to come after the filename or `--save` argument.
