### ISSUE TITLE
Release

### ISSUE THREAD

**Issue by ehristev** [fsphil/fswebcam#48]
Hi Phil,

you think you can make a new release of the software on this website ?
http://www.sanslogic.co.uk/fswebcam/

The current one is pretty old..
Thanks !

**Comment by lowcid** [comment]
yes, i would like the same. Love the simplicity of this tool, and would like a new release too.

**Comment by fsphil** [comment]
Agreed. There are a few open issues I'd like to deal with first, but I'll aim to make a release this weekend.

**Comment by fsphil** [comment]
A new release is up. Sorry for the delay. It's a weekend so I was 50% on time.

**Comment by ehristev** [comment]
Kudos !
